vim.cmd.packadd("nvim.difftool")
vim.cmd.packadd("nvim.undotree")

require("plugins.blink")
require("plugins.colorscheme")
require("plugins.conform")
require("plugins.dap")
require("plugins.hardtime")
require("plugins.lazygit")
require("plugins.linting")
require("plugins.lualine")
require("plugins.mason")
require("plugins.notify")
require("plugins.oil")
require("plugins.quicker")
require("plugins.telescope")
require("plugins.tmux-navigator")
require("plugins.treesitter")
